version: '3'
services: 
    qgis:
        build: .
        image: local/qgis-debug
        command: read
        environment: 
            # Use :99 for default XVfb
            # Use :98 for default VNC
            DISPLAY: ":99"
        ports: 
            - "${VNC_PORT}:5998"
            - "${SSH_PORT}:22"